package generate

// realisticQueries is a curated corpus of real-world-style search queries,
// ordered roughly head (very common) → tail (rare/specific). It spans the four
// classic search intents so different backend code paths get exercised:
//   - navigational (find a specific site/brand)
//   - informational (learn something: how/what/why)
//   - transactional (do/buy something: best, price, download)
//   - local (near me, in <place>)
//
// The generator samples this with a head-weighted (Zipfian-like) distribution so
// popular queries recur and the long tail stays diverse — as real traffic does.
var realisticQueries = []string{
	// --- Head: very common, mostly navigational/short informational ---
	"weather",
	"news",
	"youtube",
	"maps",
	"translate",
	"gmail login",
	"amazon",
	"wikipedia",
	"reddit",
	"calculator",
	"currency converter",
	"time zone converter",
	"speed test",
	"what time is it",
	"how to screenshot",
	"unit converter",
	"random number generator",
	"pdf to word",
	"stock market today",
	"bitcoin price",

	// --- Upper-mid: common informational ---
	"how to boil an egg",
	"how many ounces in a cup",
	"what is my ip address",
	"how to tie a tie",
	"how to take a screenshot on windows",
	"how long to boil pasta",
	"how to lose weight",
	"symptoms of the flu",
	"how to write a cover letter",
	"how to invest in stocks",
	"best programming language to learn",
	"how does the stock market work",
	"what is machine learning",
	"how to start a business",
	"how to make sourdough bread",
	"how to meditate for beginners",
	"how to improve credit score",
	"what causes climate change",
	"how do vaccines work",
	"how to learn a new language fast",

	// --- Transactional ---
	"best laptop under 1000",
	"cheap flights to new york",
	"best wireless headphones 2026",
	"buy running shoes online",
	"best budget smartphone",
	"electric car tax credit",
	"best password manager",
	"cheapest car insurance quotes",
	"best vpn for privacy",
	"download vlc media player",
	"best coffee maker with grinder",
	"noise cancelling earbuds review",
	"best mattress for back pain",
	"solar panel cost calculator",
	"best project management software",
	"standing desk under 300",
	"best mechanical keyboard for programming",
	"cheap gaming pc build",
	"best travel credit card rewards",
	"ergonomic office chair review",

	// --- Local ---
	"coffee shops near me",
	"pharmacy open now",
	"gas stations near me",
	"restaurants open late near me",
	"urgent care near me",
	"dog park near me",
	"electric car charging stations near me",
	"farmers market this weekend",
	"public library hours",
	"vegan restaurants near me",

	// --- Mid-tail: specific informational ---
	"difference between http and https",
	"how to configure a reverse proxy",
	"kubernetes vs docker swarm",
	"postgresql vs mysql performance",
	"how to set up two factor authentication",
	"what is a decentralized search engine",
	"how does a search engine index web pages",
	"privacy focused browser comparison",
	"how to run a local llm",
	"self hosted analytics alternatives to google",
	"how to reduce home energy bills",
	"beginner guitar chords chart",
	"composting for apartment dwellers",
	"intermittent fasting schedule for beginners",
	"how to read a nutrition label",
	"raspberry pi home server projects",
	"best practices for password security",
	"how to back up photos to the cloud",
	"understanding compound interest",
	"how to write clean code",

	// --- Long tail: rare, highly specific ---
	"why is my sourdough starter not rising after 5 days",
	"fix nginx 502 bad gateway upstream timeout",
	"how to migrate wordpress site to a new host without downtime",
	"quantum error correction surface codes explained simply",
	"best low light indoor plants that are safe for cats",
	"how to calibrate a 3d printer bed manually",
	"difference between mitosis and meiosis with diagrams",
	"how to remove exif metadata from photos before sharing",
	"raspberry pi zero power consumption watts idle",
	"marine biology masters programs with fieldwork in the pacific",
	"how to negotiate a lower interest rate on a car loan",
	"why do cats knead blankets before lying down",
	"best noise floor for home recording studio treatment",
	"how to read font kerning tables in typography",
	"geology of the appalachian mountains formation timeline",
	"how to set up wireguard vpn on a router",
	"is it safe to eat slightly green potatoes",
	"how deep are solar panels installed on a flat roof",
	"linguistics phonetic transcription vowel chart ipa",
	"how to store fresh basil so it lasts longer",
}
